Updated commit with class changes and additional
NWChemEx/PluginPlayer pull request #2
Opened 2024-02-19 01:51 UTC by Ethan5026

Here is an updated branch of separated, sectioned classes defining the plugin player in terms of managing plugins, the tree, module/node widgets, modules/nodes, and utility functions such as importing classes and browsing files. Additional look at eval is still needed to be decided.

2024-02-19 01:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NWChemEx/PluginPlayer?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NWChemEx/PluginPlayer?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NWChemEx/PluginPlayer?pullRequest=2) it.</sub>

2024-02-19 21:13 UTC, jwaldrop107 requested changes
Breaking the code up into smaller files and classes is definitely better. There's still some things that need further work, and not all of it is going to get done in this PR. The `TreeManager` and `NodeManager` are likely doing things that we should be depending on PluginPlay's `ModuleManager` to handle. But, focus on resolving these comments and we'll get this one merged and work on polishing everything up in subsequent PRs.

2024-02-19 21:13 UTC, jwaldrop107 commented on node_widget.py
> +                self.node_widget.y = new_y
```suggestion
            # Check if the new position is within the boundaries of the relative window
            x_within_bounds = 0 <= new_x <= self.relative_window.width - self.node_widget.width
            y_within_bounds = 0 <= new_y <= self.relative_window.height - self.node_widget.height
            if x_within_bounds or y_within_bounds:
                #changes position of the connected lines
                for line in self.node_widget.incoming_lines:
                    in_line = line[0]
                    points = in_line.points
                    x1 = new_x + 50 if x_within_bounds else points[0]
                    y1 = new_y + 50 if x_within_bounds else points[1]
                    in_line.points = [x1, y1, points[2], points[3]]
                for line in self.node_widget.outgoing_lines:
                    out_line = line[0]
                    points = out_line.points
                    x2 = new_x + 50 if x_within_bounds else points[2]
                    y2 = new_y + 50 if x_within_bounds else points[3]
                    out_line.points = [points[0], points[1], x2, y2]
                #changes node position
                self.node_widget.x = new_x
                self.node_widget.y = new_y
```
Here's a more compact way to do this. There's still a couple of "magic" values in this that should be explained. What is the repeated `+ 50` and why do we need to index `line`?

2024-02-19 21:13 UTC, jwaldrop107 commented on node_widget.py
> +        self.outgoing_lines = []
```suggestion
class DraggableWidget(BoxLayout):
    def __init__(self, **kwargs):
        self.is_dragging = False
        self.touch_x = 0
        self.touch_y = 0

        #the array holders for the visual lines connecting nodes that link outputs and inputs
        self.incoming_lines = []
        self.outgoing_lines = []
```
The more I think about it, the more I'm not a fan of using class attributes as defaults. There's a lot of possible gotchas that can come out of it without the correct security in place, and it's just simpler to move the defaults into the `__init__`.

2024-02-19 21:13 UTC, jwaldrop107 commented on node_widget.py
> +        self.description = description
A lot of these values are actually coming from the `module` itself, so it gets a bit redundant to take them in as inputs. I would keep the `module` and `module_name` inputs, and then move the logic from `TreeManager.add_node()` that unpacks all of these values.

2024-02-19 21:13 UTC, jwaldrop107 commented on tree_manager.py
> +                submod_dict=submod_dict, description=description)
See the comment about `ModuleNode.__init__`, but I would move most of this into that function.

2024-02-19 21:13 UTC, jwaldrop107 commented on run_plugin_player.py
Probably remove this, unless you intend to add something.

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_player.py
> +    def addMessage(self, message):
```suggestion
    def add_message(self, message):
```
Should be snake case.

2024-02-19 21:13 UTC, jwaldrop107 commented on utility_manager.py
> +        entry_text = self.plugin_player.root.ids.file_entry.ids.file_path_input.text
```suggestion
         #grab text from entry
        entry_text = self.plugin_player.root.ids.file_entry.ids.file_path_input.text
```
You don't need to declare the variable ahead of time.

2024-02-19 21:13 UTC, jwaldrop107 commented on utility_manager.py
> +    #load in a new plugin
```suggestion
```
Copy/paste error

2024-02-19 21:13 UTC, jwaldrop107 commented on utility_manager.py
> +        self.plugin_player = plugin_player
It looks like the functions in this class could probably all be free functions that take `plugin_player` instead of `self`. Alternatively, move the `imported_classes` member of `PluginPlayer` to this class.

2024-02-19 21:13 UTC, jwaldrop107 commented on utility_manager.py
> +        types_box.add_widget(back_button)
```suggestion
        #return to main config page or back to the add input page
        back_to_main = (key_number == -1)
        on_press_func = self.view_config if back_to_main else self.add_input            
        back_button = Button(text="Back", size_hint=(None,None), size=(40,20), on_press=on_press_func)
        back_button.id = f'{node_number}' if back_to_main else f'{node_number} {key_number}'
        types_box.add_widget(back_button)
```
Less repetition.

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_player.py
> +        logo = Image(source='NWCHEMEX_icon.png', size_hint=(None, None), size=(200, 200), pos_hint={'x': .75, 'y': 0})
```suggestion
        logo = Image(source='NWCHEMEX.png', fit_mode="fill", size_hint=(None, None), size=(200, 200), pos_hint={'right': 1, 'y': 0})
```
The [`fit_mode` option](https://kivy.org/doc/stable/api-kivy.uix.image.html#kivy.uix.image.Image.fit_mode) is probably the better way of handling the resizing. You might opt for `"contain"` instead of `"fill"`.

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_player.py
> +        resized_image.save(new_filepath)
Might not be needed if [`kivy.uix.image.Image.fit_mode`](https://kivy.org/doc/stable/api-kivy.uix.image.html#kivy.uix.image.Image.fit_mode) is sufficient in all cases. Consider removing if possible.

2024-02-19 21:13 UTC, jwaldrop107 commented on utility_manager.py
> +            return
```suggestion
        try:
            import_name = self.custom_declaration_widget.text.split()[0]
            class_name = self.custom_declaration_widget.text.split()[1]
        except Exception as e:
            self.plugin_player.addMessage("Invalid Entry, enter the blanks with a space in between from the Python import statement")
            self.plugin_player.addMessage(e)
            return
        if class_name in self.plugin_player.imported_classes:
            self.plugin_player.addMessage(f"Class type {class_name} previously imported")
            return
```
The `if` doesn't need to be nested into the `try` block.

2024-02-19 21:13 UTC, jwaldrop107 commented on utility_manager.py
> +            add_button.id = f'{node_number} {key_number}'
```suggestion
        #if its a property type assignt the id to route back to view_config,
        #otherwise route to input page
        add_button.id = f'{node_number} {key_number}'
```
The `id` is set the same way regardless of `key_number` being `-1`.

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_player.py
> +        self.savedPlugins = []
```suggestion
        self.saved_plugins = []
```
Snake case, here and in all other occurrences. Also consider moving this list to the `PluginManager`, since most of the manipulations of it occur in that case now.

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_manager.py
> +    def pluginView(self):
```suggestion
    def plugin_view(self):
```
Snake case

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_manager.py
> +                    self.pluginView()
```suggestion
                    temp_MM = pp.ModuleManager()
                    lib.load_modules(temp_MM)
                    new_plugin = PluginInfo(filename, temp_MM.keys())
                    self.plugin_player.saved_plugins.append(new_plugin)
                    self.plugin_view()
```
Snake case

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_manager.py
> +        self.modules = modules
Consider replacing this with either a [`namedTuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) or [`dataclass`](https://docs.python.org/3/library/dataclasses.html).

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_manager.py
> +            self.plugin_player.addMessage(f"Couldn't find submodule information: {e}")
(This is comment copied from my review of #1) This is repetitious. This logic can be factored into an internal function to encapsulate it. I also wonder if the `try/except`s are strictly necessary. Most of these calls should return empty if they are empty, not throw errors. (If they do throw errors, that's something we should look at changing.)

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_manager.py
> +        for i in range(3 - (number_of_added_plugins % 4) % 4):
Double modulo is redundant.

2024-02-19 21:13 UTC, jwaldrop107 commented on plugin_player.py
> +        self.imported_classes = []
Consider moving this into the `UtilityManager` class.

2024-02-19 21:13 UTC, jwaldrop107 commented on node_manager.py
> +                custom_input = eval(custom_declaration, sys.modules['__main__'].__dict__)
```suggestion
            #try to assign the variable
            #may be a security risk as it evaluates injected code
            # TODO: find eval alternative
            try:
                custom_input = eval(custom_declaration, sys.modules['__main__'].__dict__)
```
Just to have an explicit note.

2024-02-19 21:13 UTC, jwaldrop107 commented on node_manager.py
> +            ptype = eval(custom_declaration, sys.modules['__main__'].__dict__)
```suggestion
        #try to assign the variable
        #may be a security risk as it evaluates injected code
        # TODO: find eval alternative
        try:
            ptype = eval(custom_declaration, sys.modules['__main__'].__dict__)
```
Same as above.

2024-02-19 21:13 UTC, jwaldrop107 commented on node_widget_manager.py
> +    def view_config(self, instance):
I would try to break this up into a few more functions, but it can wait.

2024-02-20 01:22 UTC, Ethan5026 commented on utility_manager.py
> +        self.plugin_player = plugin_player
The issue I'm experiencing is that the utility classes route to other class functions found in `PluginPlayer`, I'm unsure how to link the functions without importing `plugin_player`

2024-02-20 01:27 UTC, Ethan5026 commented on plugin_player.py
> +        resized_image.save(new_filepath)
This function is needed for the button images like folders and node buttons, which don't have the fit_mode for background images.

2024-02-20 01:54 UTC, jwaldrop107 commented on utility_manager.py
> +        self.plugin_player = plugin_player
If you take the `plugin_player` as an input, you should still be able to interact with the utility classes on the instance, e.g.
```python
def util_function(plugin_player_input):
    plugin_player_input.a_manager.other_function()
```

2024-02-20 15:58 UTC, jwaldrop107 commented on node_widget.py
> +            return
You can take out the `return`s in the `try/except`s.

2024-02-24 19:16 UTC, Ethan5026 commented on utility_manager.py
> +        self.plugin_player = plugin_player
After a lot of testing, Kivy function calls through buttons are only allowed to pass an `instance` variable which contains the button id, no other arguments including `plugin_player_input` is allowed to be passed through for button functionality. For now, I am keeping the object of the plugin_player in the initialization of utility_class.

2024-02-28 17:05 UTC, jwaldrop107 approved these changes

2024-02-28 17:05 UTC, merged